name: Build StrongSwan IPK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex bison g++ gawk \
            gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
            python3-distutils rsync unzip zlib1g-dev file wget curl

      - name: Download OpenWrt SDK
        run: |
          SDK_URL=https://downloads.openwrt.org/releases/23.05.5/targets/ramips/mt7621/openwrt-sdk-23.05.5-ramips-mt7621_gcc-12.3.0_musl.Linux-x86_64.tar.xz
          wget $SDK_URL
          tar -xf $(basename $SDK_URL)
          SDK_DIR=$(tar -tf $(basename $SDK_URL) | head -1 | cut -f1 -d"/")
          mv "$SDK_DIR" openwrt-sdk

      - name: Update feeds
        run: |
          cd openwrt-sdk
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Patch StrongSwan to use OpenSSL
        run: |
          cd openwrt-sdk
          STRONGSWAN_MK="package/network/services/strongswan/Makefile"
          if [ -f "$STRONGSWAN_MK" ]; then
            echo "Patching $STRONGSWAN_MK to disable WolfSSL..."
            cat <<'EOF' >> "$STRONGSWAN_MK"

# Force OpenSSL instead of WolfSSL
CONFIGURE_ARGS += --with-openssl --disable-wolfssl
EOF
          else
            echo "StrongSwan Makefile not found!" && exit 1
          fi

      - name: Build StrongSwan
        run: |
          cd openwrt-sdk
          make package/strongswan/compile V=s

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: strongswan-ipk
          path: openwrt-sdk/bin/packages/**/*.ipk
