name: Build StrongSwan for OpenWrt (ASUS RT-AX53U)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential flex bison gawk gettext libncurses5-dev \
            libssl-dev python3-distutils rsync unzip zlib1g-dev file \
            wget curl

      - name: Download & extract OpenWrt SDK (23.05.5, ramips/mt7621)
        working-directory: ${{ github.workspace }}
        shell: bash
        run: |
          set -euxo pipefail
          SDK_URL="https://downloads.openwrt.org/releases/23.05.5/targets/ramips/mt7621/openwrt-sdk-23.05.5-ramips-mt7621_gcc-12.3.0_musl.Linux-x86_64.tar.xz"
          wget -q "$SDK_URL"
          TARBALL="$(basename "$SDK_URL")"
          # Extract
          tar -xf "$TARBALL"
          # Detect the extracted top-level directory and move to ./openwrt-sdk
          TOPDIR="$(tar -tf "$TARBALL" | head -1 | cut -f1 -d'/')"
          mv "$TOPDIR" openwrt-sdk

      - name: Update feeds & install StrongSwan
        working-directory: openwrt-sdk
        shell: bash
        run: |
          set -euxo pipefail
          ./scripts/feeds update -a
          ./scripts/feeds install strongswan

      - name: Configure to use OpenSSL and disable wolfSSL plugin
        working-directory: openwrt-sdk
        shell: bash
        run: |
          set -euxo pipefail
          # Fresh config
          rm -f .config
          cat >> .config <<'EOF'
          # We only care about package build flags inside the SDK.
          CONFIG_PACKAGE_strongswan=y
          CONFIG_PACKAGE_strongswan-mod-openssl=y
          # Do NOT build the wolfSSL backend
          # CONFIG_PACKAGE_strongswan-mod-wolfssl is not set

          # Ensure OpenSSL libs are present for linking
          CONFIG_PACKAGE_libopenssl=y
          CONFIG_PACKAGE_libopenssl-conf=y
          EOF
          # Expand minimal config
          make defconfig

          echo "----- Enabled StrongSwan options -----"
          grep -E 'STRONGSWAN|strongswan|OPENSSL|WOLFSSL' .config || true

      - name: Build StrongSwan (OpenSSL only)
        working-directory: openwrt-sdk
        shell: bash
        run: |
          set -euxo pipefail
          # Build only the StrongSwan package (and its selected plugins)
          make package/strongswan/compile V=s -j"$(nproc)"

      - name: Collect artifacts
        id: collect
        shell: bash
        working-directory: openwrt-sdk
        run: |
          set -euxo pipefail
          mkdir -p ../artifacts
          # Package ipks usually land under bin/packages/<arch>/base/
          find bin -type f -name 'strongswan*.ipk' -print -exec cp -v {} ../artifacts/ \;
          # Also grab libopenssl if built in this run (helpful for testing)
          find bin -type f -name 'libopenssl*.ipk' -print -exec cp -v {} ../artifacts/ \; || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: strongswan-openwrt-mt7621-openssl
          path: artifacts/*
          if-no-files-found: error
